// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/practice/:textId": {
    params: {
      "textId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/practice/:textId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/practice.tsx": {
    id: "routes/practice";
    page: "/practice/:textId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/practice": typeof import("./app/routes/practice.tsx");
};