# Generated by Django 5.2.4 on 2025-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packing_lists", "0003_remove_store_address_store_address_line1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
