# Generated by Django 5.2.4 on 2025-07-05 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0004_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='packinglist',
            name='custom_type',
            field=models.CharField(blank=True, help_text="If 'Other', specify type", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='type',
            field=models.CharField(choices=[('course', 'Course'), ('selection', 'Selection'), ('training', 'Training'), ('deployment', 'Deployment'), ('other', 'Other')], default='course', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='packinglistitem',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_lists', to='packing_lists.base'),
        ),
    ]
