# Generated by Django 5.2.4 on 2025-07-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0005_base_packinglist_custom_type_packinglist_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglistitem',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special notes or instructions', null=True),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='nsn_lin',
            field=models.CharField(blank=True, help_text='NSN/LIN or similar code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='required',
            field=models.BooleanField(default=True, help_text='Is this item required?'),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='section',
            field=models.CharField(blank=True, help_text='Section or category header', max_length=200, null=True),
        ),
    ]
