# Generated by Django 5.2.4 on 2025-07-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0006_packinglistitem_instructions_packinglistitem_nsn_lin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_in_person',
            field=models.BooleanField(default=True, help_text='Is this store a physical location?'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Is this store online?'),
        ),
    ]
