# Generated by Django 5.2.4 on 2025-07-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_lists', '0007_store_is_in_person_store_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, help_text='Store website URL', null=True),
        ),
    ]
