#!/usr/bin/env python3
"""
Generate SQL migration to import Fort Bragg buildings from GIS data into D1.

Reads: data/fort_bragg_buildings.json (Cumberland County GIS export)
Outputs: migrations/0002_import_fort_bragg_buildings.sql
"""

import json
import re
import uuid
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
DATA_FILE = os.path.join(ROOT_DIR, 'data', 'fort_bragg_buildings.json')
OUTPUT_FILE = os.path.join(ROOT_DIR, 'migrations', '0002_import_fort_bragg_buildings.sql')
INSTALLATION_ID = 'fort-bragg'

# Map GIS use types to MilNav categories
USE_TO_CATEGORY = {
    'OFFICE': 'admin',
    'ADMIN': 'admin',
    'HEADQUARTER': 'admin',
    'BARRACKS': 'barracks',
    'DINING': 'dining',
    'DFAC': 'dining',
    'MEDICAL': 'medical',
    'HOSPITAL': 'medical',
    'DENTAL': 'medical',
    'CHAPEL': 'religious',
    'RELIGIOUS': 'religious',
    'RECREATION': 'recreation',
    'GYM': 'recreation',
    'FITNESS': 'recreation',
    'EXCHANGE': 'retail',
    'COMMISSARY': 'retail',
    'PX': 'retail',
    'RETAIL': 'retail',
    'STORAGE': 'storage',
    'GENERAL_STORAGE': 'storage',
    'WAREHOUSE': 'storage',
    'MAINTENANCE': 'maintenance',
    'MOTOR_POOL': 'maintenance',
    'PARKING': 'parking',
    'SECURITY': 'security',
    'HAZARDOUS_MAT': 'hazmat',
    'TRAINING': 'training',
    'SCHOOL': 'education',
    'EDUCATION': 'education',
    'CHILD_DEV': 'childcare',
    'HOUSING': 'housing',
    'FAMILY_HSG': 'housing',
    'TBD': 'other',
}


def categorize(use_type, name):
    """Map GIS use type to MilNav category."""
    if not use_type:
        use_type = ''
    use_upper = use_type.strip().upper()

    # Direct match
    if use_upper in USE_TO_CATEGORY:
        return USE_TO_CATEGORY[use_upper]

    # Partial match
    for key, cat in USE_TO_CATEGORY.items():
        if key in use_upper:
            return cat

    # Try name-based categorization
    if name:
        name_upper = name.upper()
        if any(w in name_upper for w in ['DFAC', 'DINING', 'CAFE']):
            return 'dining'
        if any(w in name_upper for w in ['HOSPITAL', 'CLINIC', 'MEDICAL', 'DENTAL']):
            return 'medical'
        if any(w in name_upper for w in ['CHAPEL', 'CHURCH']):
            return 'religious'
        if any(w in name_upper for w in ['GYM', 'FITNESS', 'POOL']):
            return 'recreation'
        if any(w in name_upper for w in ['EXCHANGE', 'PX', 'COMMISSARY', 'SHOPPETTE']):
            return 'retail'
        if any(w in name_upper for w in ['BARRACKS', 'BEQ', 'BOQ']):
            return 'barracks'
        if any(w in name_upper for w in ['SCHOOL', 'ACADEMY', 'EDUCATION']):
            return 'education'

    return 'other'


def escape_sql(s):
    """Escape single quotes for SQL."""
    if s is None:
        return ''
    return str(s).replace("'", "''").strip()


def main():
    with open(DATA_FILE) as f:
        buildings = json.load(f)

    print(f"Total buildings in GIS data: {len(buildings)}")

    # Filter to importable buildings
    importable = []
    seen = set()
    skipped_no_number = 0
    skipped_no_gps = 0
    skipped_duplicate = 0

    for b in buildings:
        bldg_no = b.get('building_no')
        if not bldg_no or not bldg_no.strip():
            skipped_no_number += 1
            continue

        bldg_no = bldg_no.strip()

        lat = b.get('lat')
        lon = b.get('lon')
        if not lat or not lon or lat < 34 or lat > 36:
            skipped_no_gps += 1
            continue

        # Deduplicate by building number
        if bldg_no in seen:
            skipped_duplicate += 1
            continue
        seen.add(bldg_no)

        name = b.get('name', '')
        if name:
            name = name.strip()
        use_type = b.get('use', '')
        category = categorize(use_type, name)

        importable.append({
            'building_number': bldg_no,
            'name': name if name else None,
            'latitude': lat,
            'longitude': lon,
            'category': category,
        })

    print(f"Importable: {len(importable)}")
    print(f"Skipped - no number: {skipped_no_number}")
    print(f"Skipped - no GPS: {skipped_no_gps}")
    print(f"Skipped - duplicate: {skipped_duplicate}")

    # Generate SQL
    lines = []
    lines.append("-- MilNav: Import Fort Bragg buildings from Cumberland County GIS")
    lines.append(f"-- Source: Cumberland County GIS REST Service (BraggData/MapServer)")
    lines.append(f"-- Total buildings: {len(importable)}")
    lines.append(f"-- Generated by scripts/generate-import-sql.py")
    lines.append("")
    lines.append("-- Use INSERT OR IGNORE to avoid conflicts with existing data")
    lines.append("")

    # Batch inserts (D1 has limits, do 50 per statement)
    BATCH_SIZE = 50
    for i in range(0, len(importable), BATCH_SIZE):
        batch = importable[i:i + BATCH_SIZE]
        lines.append(f"-- Batch {i // BATCH_SIZE + 1} ({i + 1} to {i + len(batch)})")

        for b in batch:
            bid = str(uuid.uuid5(uuid.NAMESPACE_URL, f"milnav:fort-bragg:{b['building_number']}"))
            name_sql = f"'{escape_sql(b['name'])}'" if b['name'] else 'NULL'
            lines.append(
                f"INSERT OR IGNORE INTO buildings (id, installation_id, building_number, name, latitude, longitude, category, source, verified) "
                f"VALUES ('{bid}', '{INSTALLATION_ID}', '{escape_sql(b['building_number'])}', "
                f"{name_sql}, {b['latitude']:.7f}, {b['longitude']:.7f}, "
                f"'{b['category']}', 'official', 1);"
            )
        lines.append("")

    sql = '\n'.join(lines)

    with open(OUTPUT_FILE, 'w') as f:
        f.write(sql)

    print(f"\nGenerated: {OUTPUT_FILE}")
    print(f"SQL statements: {len(importable)}")

    # Category breakdown
    from collections import Counter
    cats = Counter(b['category'] for b in importable)
    print(f"\nCategory breakdown:")
    for cat, count in cats.most_common():
        print(f"  {cat}: {count}")


if __name__ == '__main__':
    main()
