name = "milnav"
main = "api/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "milnav-db"
database_id = "607c5700-8a1d-4333-b34a-d6a75a3f1a5a"

[placement]
mode = "smart"

[observability]
enabled = true

[vars]
TIMEZONE = "America/New_York"
